use sdl2::keyboard::Keycode;
use serde::Deserialize;

#[derive(Deserialize)]
pub struct Controls {
  jump_key: MyKeycode,
  left_key: MyKeycode,
  right_key: MyKeycode,
  up_key: MyKeycode,
  down_key: MyKeycode,
  sprint_key: MyKeycode,
  shoot_key: MyKeycode,
  zoom_in_key: MyKeycode,
  zoom_out_key: MyKeycode,
  pause_key: MyKeycode,
  edit_mode_key: MyKeycode,
}

pub struct SDLControls {
  pub jump_key: Keycode,
  pub left_key: Keycode,
  pub right_key: Keycode,
  pub up_key: Keycode,
  pub down_key: Keycode,
  pub sprint_key: Keycode,
  pub shoot_key: Keycode,
  pub zoom_in_key: Keycode,
  pub zoom_out_key: Keycode,
  pub pause_key: Keycode,
  pub edit_mode_key: Keycode,
}

impl Controls {
  pub fn deserialize(serialized: String) -> Self {
    serde_json::from_str(&serialized).unwrap()
  }
  pub fn to_sdl_keycodes(self) -> SDLControls {
    SDLControls {
      jump_key: self.jump_key.into(),
      left_key: self.left_key.into(),
      right_key: self.right_key.into(),
      up_key: self.up_key.into(),
      down_key: self.down_key.into(),
      sprint_key: self.sprint_key.into(),
      shoot_key: self.shoot_key.into(),
      zoom_in_key: self.zoom_in_key.into(),
      zoom_out_key: self.zoom_out_key.into(),
      pause_key: self.pause_key.into(),
      edit_mode_key: self.edit_mode_key.into(),
    }
  }
}

#[derive(Deserialize)]
enum MyKeycode {
  Backspace,
  Tab,
  Return,
  Escape,
  Space,
  Exclaim,
  Quotedbl,
  Hash,
  Dollar,
  Percent,
  Ampersand,
  Quote,
  LeftParen,
  RightParen,
  Asterisk,
  Plus,
  Comma,
  Minus,
  Period,
  Slash,
  Num0,
  Num1,
  Num2,
  Num3,
  Num4,
  Num5,
  Num6,
  Num7,
  Num8,
  Num9,
  Colon,
  Semicolon,
  Less,
  Equals,
  Greater,
  Question,
  At,
  LeftBracket,
  Backslash,
  RightBracket,
  Caret,
  Underscore,
  Backquote,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  Delete,
  CapsLock,
  F1,
  F2,
  F3,
  F4,
  F5,
  F6,
  F7,
  F8,
  F9,
  F10,
  F11,
  F12,
  PrintScreen,
  ScrollLock,
  Pause,
  Insert,
  Home,
  PageUp,
  End,
  PageDown,
  Right,
  Left,
  Down,
  Up,
  NumLockClear,
  KpDivide,
  KpMultiply,
  KpMinus,
  KpPlus,
  KpEnter,
  Kp1,
  Kp2,
  Kp3,
  Kp4,
  Kp5,
  Kp6,
  Kp7,
  Kp8,
  Kp9,
  Kp0,
  KpPeriod,
  Application,
  Power,
  KpEquals,
  F13,
  F14,
  F15,
  F16,
  F17,
  F18,
  F19,
  F20,
  F21,
  F22,
  F23,
  F24,
  Execute,
  Help,
  Menu,
  Select,
  Stop,
  Again,
  Undo,
  Cut,
  Copy,
  Paste,
  Find,
  Mute,
  VolumeUp,
  VolumeDown,
  KpComma,
  KpEqualsAS400,
  AltErase,
  Sysreq,
  Cancel,
  Clear,
  Prior,
  Return2,
  Separator,
  Out,
  Oper,
  ClearAgain,
  CrSel,
  ExSel,
  Kp00,
  Kp000,
  ThousandsSeparator,
  DecimalSeparator,
  CurrencyUnit,
  CurrencySubUnit,
  KpLeftParen,
  KpRightParen,
  KpLeftBrace,
  KpRightBrace,
  KpTab,
  KpBackspace,
  KpA,
  KpB,
  KpC,
  KpD,
  KpE,
  KpF,
  KpXor,
  KpPower,
  KpPercent,
  KpLess,
  KpGreater,
  KpAmpersand,
  KpDblAmpersand,
  KpVerticalBar,
  KpDblVerticalBar,
  KpColon,
  KpHash,
  KpSpace,
  KpAt,
  KpExclam,
  KpMemStore,
  KpMemRecall,
  KpMemClear,
  KpMemAdd,
  KpMemSubtract,
  KpMemMultiply,
  KpMemDivide,
  KpPlusMinus,
  KpClear,
  KpClearEntry,
  KpBinary,
  KpOctal,
  KpDecimal,
  KpHexadecimal,
  LCtrl,
  LShift,
  LAlt,
  LGui,
  RCtrl,
  RShift,
  RAlt,
  RGui,
  Mode,
  AudioNext,
  AudioPrev,
  AudioStop,
  AudioPlay,
  AudioMute,
  MediaSelect,
  Www,
  Mail,
  Calculator,
  Computer,
  AcSearch,
  AcHome,
  AcBack,
  AcForward,
  AcStop,
  AcRefresh,
  AcBookmarks,
  BrightnessDown,
  BrightnessUp,
  DisplaySwitch,
  KbdIllumToggle,
  KbdIllumDown,
  KbdIllumUp,
  Eject,
  Sleep,
}

impl Into<Keycode> for MyKeycode {
  fn into(self: Self) -> Keycode {
    match self {
      MyKeycode::Backspace => Keycode::Backspace,
      MyKeycode::Tab => Keycode::Tab,
      MyKeycode::Return => Keycode::Return,
      MyKeycode::Escape => Keycode::Escape,
      MyKeycode::Space => Keycode::Space,
      MyKeycode::Exclaim => Keycode::Exclaim,
      MyKeycode::Quotedbl => Keycode::Quotedbl,
      MyKeycode::Hash => Keycode::Hash,
      MyKeycode::Dollar => Keycode::Dollar,
      MyKeycode::Percent => Keycode::Percent,
      MyKeycode::Ampersand => Keycode::Ampersand,
      MyKeycode::Quote => Keycode::Quote,
      MyKeycode::LeftParen => Keycode::LeftParen,
      MyKeycode::RightParen => Keycode::RightParen,
      MyKeycode::Asterisk => Keycode::Asterisk,
      MyKeycode::Plus => Keycode::Plus,
      MyKeycode::Comma => Keycode::Comma,
      MyKeycode::Minus => Keycode::Minus,
      MyKeycode::Period => Keycode::Period,
      MyKeycode::Slash => Keycode::Slash,
      MyKeycode::Num0 => Keycode::Num0,
      MyKeycode::Num1 => Keycode::Num1,
      MyKeycode::Num2 => Keycode::Num2,
      MyKeycode::Num3 => Keycode::Num3,
      MyKeycode::Num4 => Keycode::Num4,
      MyKeycode::Num5 => Keycode::Num5,
      MyKeycode::Num6 => Keycode::Num6,
      MyKeycode::Num7 => Keycode::Num7,
      MyKeycode::Num8 => Keycode::Num8,
      MyKeycode::Num9 => Keycode::Num9,
      MyKeycode::Colon => Keycode::Colon,
      MyKeycode::Semicolon => Keycode::Semicolon,
      MyKeycode::Less => Keycode::Less,
      MyKeycode::Equals => Keycode::Equals,
      MyKeycode::Greater => Keycode::Greater,
      MyKeycode::Question => Keycode::Question,
      MyKeycode::At => Keycode::At,
      MyKeycode::LeftBracket => Keycode::LeftBracket,
      MyKeycode::Backslash => Keycode::Backslash,
      MyKeycode::RightBracket => Keycode::RightBracket,
      MyKeycode::Caret => Keycode::Caret,
      MyKeycode::Underscore => Keycode::Underscore,
      MyKeycode::Backquote => Keycode::Backquote,
      MyKeycode::A => Keycode::A,
      MyKeycode::B => Keycode::B,
      MyKeycode::C => Keycode::C,
      MyKeycode::D => Keycode::D,
      MyKeycode::E => Keycode::E,
      MyKeycode::F => Keycode::F,
      MyKeycode::G => Keycode::G,
      MyKeycode::H => Keycode::H,
      MyKeycode::I => Keycode::I,
      MyKeycode::J => Keycode::J,
      MyKeycode::K => Keycode::K,
      MyKeycode::L => Keycode::L,
      MyKeycode::M => Keycode::M,
      MyKeycode::N => Keycode::N,
      MyKeycode::O => Keycode::O,
      MyKeycode::P => Keycode::P,
      MyKeycode::Q => Keycode::Q,
      MyKeycode::R => Keycode::R,
      MyKeycode::S => Keycode::S,
      MyKeycode::T => Keycode::T,
      MyKeycode::U => Keycode::U,
      MyKeycode::V => Keycode::V,
      MyKeycode::W => Keycode::W,
      MyKeycode::X => Keycode::X,
      MyKeycode::Y => Keycode::Y,
      MyKeycode::Z => Keycode::Z,
      MyKeycode::Delete => Keycode::Delete,
      MyKeycode::CapsLock => Keycode::CapsLock,
      MyKeycode::F1 => Keycode::F1,
      MyKeycode::F2 => Keycode::F2,
      MyKeycode::F3 => Keycode::F3,
      MyKeycode::F4 => Keycode::F4,
      MyKeycode::F5 => Keycode::F5,
      MyKeycode::F6 => Keycode::F6,
      MyKeycode::F7 => Keycode::F7,
      MyKeycode::F8 => Keycode::F8,
      MyKeycode::F9 => Keycode::F9,
      MyKeycode::F10 => Keycode::F10,
      MyKeycode::F11 => Keycode::F11,
      MyKeycode::F12 => Keycode::F12,
      MyKeycode::PrintScreen => Keycode::PrintScreen,
      MyKeycode::ScrollLock => Keycode::ScrollLock,
      MyKeycode::Pause => Keycode::Pause,
      MyKeycode::Insert => Keycode::Insert,
      MyKeycode::Home => Keycode::Home,
      MyKeycode::PageUp => Keycode::PageUp,
      MyKeycode::End => Keycode::End,
      MyKeycode::PageDown => Keycode::PageDown,
      MyKeycode::Right => Keycode::Right,
      MyKeycode::Left => Keycode::Left,
      MyKeycode::Down => Keycode::Down,
      MyKeycode::Up => Keycode::Up,
      MyKeycode::NumLockClear => Keycode::NumLockClear,
      MyKeycode::KpDivide => Keycode::KpDivide,
      MyKeycode::KpMultiply => Keycode::KpMultiply,
      MyKeycode::KpMinus => Keycode::KpMinus,
      MyKeycode::KpPlus => Keycode::KpPlus,
      MyKeycode::KpEnter => Keycode::KpEnter,
      MyKeycode::Kp1 => Keycode::Kp1,
      MyKeycode::Kp2 => Keycode::Kp2,
      MyKeycode::Kp3 => Keycode::Kp3,
      MyKeycode::Kp4 => Keycode::Kp4,
      MyKeycode::Kp5 => Keycode::Kp5,
      MyKeycode::Kp6 => Keycode::Kp6,
      MyKeycode::Kp7 => Keycode::Kp7,
      MyKeycode::Kp8 => Keycode::Kp8,
      MyKeycode::Kp9 => Keycode::Kp9,
      MyKeycode::Kp0 => Keycode::Kp0,
      MyKeycode::KpPeriod => Keycode::KpPeriod,
      MyKeycode::Application => Keycode::Application,
      MyKeycode::Power => Keycode::Power,
      MyKeycode::KpEquals => Keycode::KpEquals,
      MyKeycode::F13 => Keycode::F13,
      MyKeycode::F14 => Keycode::F14,
      MyKeycode::F15 => Keycode::F15,
      MyKeycode::F16 => Keycode::F16,
      MyKeycode::F17 => Keycode::F17,
      MyKeycode::F18 => Keycode::F18,
      MyKeycode::F19 => Keycode::F19,
      MyKeycode::F20 => Keycode::F20,
      MyKeycode::F21 => Keycode::F21,
      MyKeycode::F22 => Keycode::F22,
      MyKeycode::F23 => Keycode::F23,
      MyKeycode::F24 => Keycode::F24,
      MyKeycode::Execute => Keycode::Execute,
      MyKeycode::Help => Keycode::Help,
      MyKeycode::Menu => Keycode::Menu,
      MyKeycode::Select => Keycode::Select,
      MyKeycode::Stop => Keycode::Stop,
      MyKeycode::Again => Keycode::Again,
      MyKeycode::Undo => Keycode::Undo,
      MyKeycode::Cut => Keycode::Cut,
      MyKeycode::Copy => Keycode::Copy,
      MyKeycode::Paste => Keycode::Paste,
      MyKeycode::Find => Keycode::Find,
      MyKeycode::Mute => Keycode::Mute,
      MyKeycode::VolumeUp => Keycode::VolumeUp,
      MyKeycode::VolumeDown => Keycode::VolumeDown,
      MyKeycode::KpComma => Keycode::KpComma,
      MyKeycode::KpEqualsAS400 => Keycode::KpEqualsAS400,
      MyKeycode::AltErase => Keycode::AltErase,
      MyKeycode::Sysreq => Keycode::Sysreq,
      MyKeycode::Cancel => Keycode::Cancel,
      MyKeycode::Clear => Keycode::Clear,
      MyKeycode::Prior => Keycode::Prior,
      MyKeycode::Return2 => Keycode::Return2,
      MyKeycode::Separator => Keycode::Separator,
      MyKeycode::Out => Keycode::Out,
      MyKeycode::Oper => Keycode::Oper,
      MyKeycode::ClearAgain => Keycode::ClearAgain,
      MyKeycode::CrSel => Keycode::CrSel,
      MyKeycode::ExSel => Keycode::ExSel,
      MyKeycode::Kp00 => Keycode::Kp00,
      MyKeycode::Kp000 => Keycode::Kp000,
      MyKeycode::ThousandsSeparator => Keycode::ThousandsSeparator,
      MyKeycode::DecimalSeparator => Keycode::DecimalSeparator,
      MyKeycode::CurrencyUnit => Keycode::CurrencyUnit,
      MyKeycode::CurrencySubUnit => Keycode::CurrencySubUnit,
      MyKeycode::KpLeftParen => Keycode::KpLeftParen,
      MyKeycode::KpRightParen => Keycode::KpRightParen,
      MyKeycode::KpLeftBrace => Keycode::KpLeftBrace,
      MyKeycode::KpRightBrace => Keycode::KpRightBrace,
      MyKeycode::KpTab => Keycode::KpTab,
      MyKeycode::KpBackspace => Keycode::KpBackspace,
      MyKeycode::KpA => Keycode::KpA,
      MyKeycode::KpB => Keycode::KpB,
      MyKeycode::KpC => Keycode::KpC,
      MyKeycode::KpD => Keycode::KpD,
      MyKeycode::KpE => Keycode::KpE,
      MyKeycode::KpF => Keycode::KpF,
      MyKeycode::KpXor => Keycode::KpXor,
      MyKeycode::KpPower => Keycode::KpPower,
      MyKeycode::KpPercent => Keycode::KpPercent,
      MyKeycode::KpLess => Keycode::KpLess,
      MyKeycode::KpGreater => Keycode::KpGreater,
      MyKeycode::KpAmpersand => Keycode::KpAmpersand,
      MyKeycode::KpDblAmpersand => Keycode::KpDblAmpersand,
      MyKeycode::KpVerticalBar => Keycode::KpVerticalBar,
      MyKeycode::KpDblVerticalBar => Keycode::KpDblVerticalBar,
      MyKeycode::KpColon => Keycode::KpColon,
      MyKeycode::KpHash => Keycode::KpHash,
      MyKeycode::KpSpace => Keycode::KpSpace,
      MyKeycode::KpAt => Keycode::KpAt,
      MyKeycode::KpExclam => Keycode::KpExclam,
      MyKeycode::KpMemStore => Keycode::KpMemStore,
      MyKeycode::KpMemRecall => Keycode::KpMemRecall,
      MyKeycode::KpMemClear => Keycode::KpMemClear,
      MyKeycode::KpMemAdd => Keycode::KpMemAdd,
      MyKeycode::KpMemSubtract => Keycode::KpMemSubtract,
      MyKeycode::KpMemMultiply => Keycode::KpMemMultiply,
      MyKeycode::KpMemDivide => Keycode::KpMemDivide,
      MyKeycode::KpPlusMinus => Keycode::KpPlusMinus,
      MyKeycode::KpClear => Keycode::KpClear,
      MyKeycode::KpClearEntry => Keycode::KpClearEntry,
      MyKeycode::KpBinary => Keycode::KpBinary,
      MyKeycode::KpOctal => Keycode::KpOctal,
      MyKeycode::KpDecimal => Keycode::KpDecimal,
      MyKeycode::KpHexadecimal => Keycode::KpHexadecimal,
      MyKeycode::LCtrl => Keycode::LCtrl,
      MyKeycode::LShift => Keycode::LShift,
      MyKeycode::LAlt => Keycode::LAlt,
      MyKeycode::LGui => Keycode::LGui,
      MyKeycode::RCtrl => Keycode::RCtrl,
      MyKeycode::RShift => Keycode::RShift,
      MyKeycode::RAlt => Keycode::RAlt,
      MyKeycode::RGui => Keycode::RGui,
      MyKeycode::Mode => Keycode::Mode,
      MyKeycode::AudioNext => Keycode::AudioNext,
      MyKeycode::AudioPrev => Keycode::AudioPrev,
      MyKeycode::AudioStop => Keycode::AudioStop,
      MyKeycode::AudioPlay => Keycode::AudioPlay,
      MyKeycode::AudioMute => Keycode::AudioMute,
      MyKeycode::MediaSelect => Keycode::MediaSelect,
      MyKeycode::Www => Keycode::Www,
      MyKeycode::Mail => Keycode::Mail,
      MyKeycode::Calculator => Keycode::Calculator,
      MyKeycode::Computer => Keycode::Computer,
      MyKeycode::AcSearch => Keycode::AcSearch,
      MyKeycode::AcHome => Keycode::AcHome,
      MyKeycode::AcBack => Keycode::AcBack,
      MyKeycode::AcForward => Keycode::AcForward,
      MyKeycode::AcStop => Keycode::AcStop,
      MyKeycode::AcRefresh => Keycode::AcRefresh,
      MyKeycode::AcBookmarks => Keycode::AcBookmarks,
      MyKeycode::BrightnessDown => Keycode::BrightnessDown,
      MyKeycode::BrightnessUp => Keycode::BrightnessUp,
      MyKeycode::DisplaySwitch => Keycode::DisplaySwitch,
      MyKeycode::KbdIllumToggle => Keycode::KbdIllumToggle,
      MyKeycode::KbdIllumDown => Keycode::KbdIllumDown,
      MyKeycode::KbdIllumUp => Keycode::KbdIllumUp,
      MyKeycode::Eject => Keycode::Eject,
      MyKeycode::Sleep => Keycode::Sleep,
    }
  }
}
